config/routes.rb
Rails.application.routes.draw do
  resources :orders
  resources :line_items
  resources :carts
  resources :media
  resources :genres
  devise_for :users
  resources :listings
  resources :posts

  resources :users, only: [:index]

  resources :messages, only: [:new, :create]

  resources :conversations do
    member do
      post :reply
      post :trash
      post :untrash
    end
  end


  # resources :conversations, only: [:index, :show, :destroy] do
  #   member do
  #     post :restore
  #   end
  # end
  # resources :conversations, only: [:index, :show, :destroy] do
  #   collection do
  #     delete :empty_trash
  #   end
  # end
  # resources :conversations, only: [:index, :show, :destroy] do
  #   member do
  #     post :reply
  #   end
  # end
  # resources :conversations, only: [:index, :show, :destroy] do
  #   member do
  #     post :mark_as_read
  #   end
  # end

  # mailbox folder routes
  get "mailbox/inbox" => "mailbox#inbox", as: :mailbox_inbox
  get "mailbox/sent" => "mailbox#sent", as: :mailbox_sent
  get "mailbox/trash" => "mailbox#trash", as: :mailbox_trash
  
  get 'pages/about'
  get 'pages/contact'
  get 'seller' => 'listings#seller'

  root 'listings#index'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/listing.rb
class Listing < ApplicationRecord
    before_destroy :not_referenced_by_any_line_item
    has_one_attached :image 
    has_and_belongs_to_many :types
    has_and_belongs_to_many :media

    has_many :line_items


    validates :name, :description, :price, presence: true
    validates :price, numericality: { greater_than: 0 }
    validates :image, attached: true, content_type: ['image/png', 'image/jpg', 'image/jpeg']

    belongs_to :user
    self.per_page = 10

    private
    def not_referenced_by_any_line_item
        unless line_items.empty?
            errors.add(:base, "Line items present")
            throw :abort
        end
    end

end

app/models/listings_type.rb
class ListingsType < ApplicationRecord
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :set_listing, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:seller, :new, :create, :edit, :update, :destroy]
  before_action :check_user, only: [:edit, :update, :destroy]

  # GET /listings for particular seller
  def seller
    @listings = Listing.where(user: current_user).order("created_at DESC")
  end

  # GET /listings
  # GET /listings.json
  def index
    @listings = Listing.all.order("created_at DESC").paginate(page: params[:page], per_page: 8)
  end

  # GET /listings/1
  # GET /listings/1.json
  def show
    @listing = Listing.find(params[:id])
    @types = Type.where(:listing_id => @listing).all  
  end

  # GET /listings/new
  def new
    @listing = Listing.new
  end

  # GET /listings/1/edit
  def edit
  end

  # POST /listings
  # POST /listings.json
  def create
    @listing = Listing.new(listing_params)
    @listing.user_id = current_user.id
    # puts 'your debug message'
    # listing_params[:listing][:type_ids].each do |t|
    #   puts 'in the loop'
    # end

    # @listing.types << Type.first
    # @listing.types << Type.last


    respond_to do |format|
      if @listing.save
        # add genres (also add a version of this to update) 
          # How will you deal with people deleting listings? Woo, this is a tough issue!
        #listing_params.genres.each do |p|
          # Genre.where(genre_id == p.genre_id) << @listing
        #end
        format.html { redirect_to @listing, notice: 'Listing was successfully created.' }
        format.json { render :show, status: :created, location: @listing }
      else
        format.html { render :new }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /listings/1
  # PATCH/PUT /listings/1.json
  def update
    respond_to do |format|
      if @listing.update(listing_params)
        format.html { redirect_to @listing, notice: 'Listing was successfully updated.' }
        format.json { render :show, status: :ok, location: @listing }
      else
        format.html { render :edit }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /listings/1
  # DELETE /listings/1.json
  def destroy
    @listing.destroy
    respond_to do |format|
      format.html { redirect_to listings_url, notice: 'Listing was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_listing
      @listing = Listing.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def listing_params
      params.require(:listing).permit(:name, :description, :price, :image, :type_ids, medium_ids:[])
    end

    #Only allow users to edit, update or destroy listings that belong to them
    def check_user
      if current_user != @listing.user
        redirect_to root_url, alert: "Sorry, this listing belongs to someone else"
      end
    end
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/views/listings/_form.html.erb
<%= form_with(model: listing, :html => { :multipart => true},local: true) do |form| %>
  <% if listing.errors.any? %>
    <div id="error" class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <h4><%= pluralize(listing.errors.count, "error") %> prohibited this listing from being saved:</h4>

      <ul>
        <% listing.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :image %>
    <%= form.file_field :image, class: "form-control"  %>
  </div>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: "form-control"  %>
  </div>

  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_area :description, class: "form-control"  %>
  </div>

  <div class="form-group">
    <%= form.label :price %>
    <%= form.text_field :price, class: "form-control"  %>
  </div>

  <div class="field">
    <%= form.label "Medium" %><br />
    <%= form.collection_check_boxes :medium_ids, Medium.all, :id, :name do |b| %>
      <div class="collection-check-box">
          <%= b.check_box %>
          <%= b.label %>
      </div>
    <% end %>
    </div>

  <div class="form-group">
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/listings/edit.html.erb
<h1>Editing Listing</h1>

<%= render 'form', listing: @listing %>

<%= link_to 'Show', @listing, class: "btn btn-link" %> |
<%= link_to 'Back', listings_path, class: "btn btn-link" %>

app/views/listings/index.html.erb
<div class="jumbotron">
  <h1>Self-publishing from around the world.</h1>
  <h2>Discover one-of-a-kind zines</h2>
</div>
<div class="center">
  <div class="row">
    <% @listings.each do |listing| %>  
      <div class="col-12 col-sm-6 col-md-3" >
        <div class="card">
          <div class="card-body">
            <%= link_to image_tag(listing.image.variant(resize_to_fill: [400, 600]).processed, class: 'limited'), listing %>  <%# %>
            <div class="caption">
              <h3><%= listing.name %></h3>  
              <p><%= number_to_currency(listing.price) %></p>  
              <p><%= "Sold by #{listing.user.name}" %> </p>  
              <% if (user_signed_in?) && (current_user == listing.user) %>
              <% end %>  
            </div>
          </div>
        </div>
      </div>
    <% end %> 
  </div>
</div>
<br>
<%= will_paginate(@things, :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer) %>

<% if user_signed_in? %>
  <%= link_to 'New Listing', new_listing_path, class: "btn btn-link" %>
  <% end %>

app/views/listings/new.html.erb
<h1>New Listing</h1>

<%= render 'form', listing: @listing %>

<%= link_to 'Back', listings_path, class: "btn btn-link" %>

app/views/listings/seller.html.erb
<table class="tablee">
<thead class="">
  <tr>
    <th class="center">Image</th>
    <th class="center">Name</th>
    <th class="center">Description</th>
    <th class="center">Price</th>
    <th class="center">View | Edit | Delete</th>
  </tr>
<thead>
	<tbody>

  <% @listings.each do |listing| %>
    <tr>
      <%# <td><%= link_to image_tag(listing.image, size:100), listing %>
      <td><%= link_to image_tag(listing.image.variant(resize_to_fill: [100, 100]).processed), listing, class: "mx-auto" %></td>
      <td><%= listing.name %></td>
      <td><%= listing.description %></td>
      <td><%= number_to_currency(listing.price) %></td>
      <td>
        <div class="btn-group">
          <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
            Options <span class="caret"></span>
          </button>
          <ul class="dropdown-menu" role="menu">
            <li><%= link_to "View", listing, class: "btn btn-link" %></li>
            <li><%= link_to "Edit", edit_listing_path(listing), class: "btn btn-link" %></li>
            <li><%= link_to 'Delete', listing, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-link" %></li>
          </ul>
        </div>
      </td>
    </tr>
  <% end %>
  	</tbody>

</table>

<% if user_signed_in? %>
  <%= link_to 'New Listing', new_listing_path, class: "btn btn-link" %>
<% end %>

app/views/listings/show.html.erb
<div class="row">
  <div class="col-md-6">
     <div class="img-thumbnail">
        <%= image_tag(@listing.image, style:'width:100%')%>
        <%# <%= link_to image_tag(@listing.image, style:'width:100%'), listings_path %> 
     </div>
  </div>
  <div class="col-md-6">
    <h3><%= @listing.name %></h3>
    <h5><%= number_to_currency(@listing.price) %></h5>
    <p><%= @listing.description %></p> <%# Style this so that it is in its own box. %>
    <p> Created by:</p>
    <p> Publication type: 
      <% @listing.types.each do |t|%>  
        <%= t.name %>
      <%end%> 
    </p>
    <p> Subject:</p>
    <p> Media: 
      <% @listing.media.each do |m|%>  
        <%= m.name %>
      <%end%> 
    </p>
    <p> In Stock: Yes/No </p>    <%# In stock if quantity is greater than 1, else out of stock %>
    <%= button_to 'Add to cart', line_items_path(listing_id: @listing), class: 'btn btn-warning add-to-cart'%>
  </div>
</div>




<% if current_user == @listing.user %>
  <%= link_to 'Edit', edit_listing_path(@listing), class: "btn btn-link" %> |
<% end %>
<%= link_to 'Back', listings_path, class: "btn btn-link" %>