config/routes.rb
Rails.application.routes.draw do
  resources :orders
  resources :line_items
  resources :carts
  resources :media
  resources :genres
  devise_for :users
  resources :listings
  resources :posts

  resources :users, only: [:index]

  resources :messages, only: [:new, :create]

  resources :conversations do
    member do
      post :reply
      post :trash
      post :untrash
    end
  end


  # resources :conversations, only: [:index, :show, :destroy] do
  #   member do
  #     post :restore
  #   end
  # end
  # resources :conversations, only: [:index, :show, :destroy] do
  #   collection do
  #     delete :empty_trash
  #   end
  # end
  # resources :conversations, only: [:index, :show, :destroy] do
  #   member do
  #     post :reply
  #   end
  # end
  # resources :conversations, only: [:index, :show, :destroy] do
  #   member do
  #     post :mark_as_read
  #   end
  # end

  # mailbox folder routes
  get "mailbox/inbox" => "mailbox#inbox", as: :mailbox_inbox
  get "mailbox/sent" => "mailbox#sent", as: :mailbox_sent
  get "mailbox/trash" => "mailbox#trash", as: :mailbox_trash
  
  get 'pages/about'
  get 'pages/contact'
  get 'seller' => 'listings#seller'

  root 'listings#index'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
    has_many :line_items, dependent: :destroy

    def add_listing(listing)
        current_item = line_items.find_by(listing_id: listing.id)
        if current_item
            current_item.increment(:quantity)
        else
            current_item = line_items.build(listing_id: listing.id)
        end
        current_item
    end

    def total_price
        line_items.to_a.sum { |item| item.total_price } 
    end
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :listing
  belongs_to :cart, optional: true
  belongs_to :order, optional: true

  def total_price
    listing.price * quantity.to_i
  end
end

app/models/listing.rb
class Listing < ApplicationRecord
    before_destroy :not_referenced_by_any_line_item
    has_one_attached :image 
    has_and_belongs_to_many :types
    has_and_belongs_to_many :media

    has_many :line_items


    validates :name, :description, :price, presence: true
    validates :price, numericality: { greater_than: 0 }
    validates :image, attached: true, content_type: ['image/png', 'image/jpg', 'image/jpeg']

    belongs_to :user
    self.per_page = 10

    private
    def not_referenced_by_any_line_item
        unless line_items.empty?
            errors.add(:base, "Line items present")
            throw :abort
        end
    end

end

app/models/listings_type.rb
class ListingsType < ApplicationRecord
end

app/models/medium.rb
class Medium < ApplicationRecord
    has_and_belongs_to_many :listings
end

app/models/order.rb
class Order < ApplicationRecord
    validates :address, :city, :state, presence: true
    
    # belongs_to :cart
    has_many :line_items, dependent: :destroy

end

app/models/type.rb
class Type < ApplicationRecord
    has_and_belongs_to_many :listings

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  acts_as_messageable
  
  def mailboxer_name
    self.name
  end

  def mailboxer_email(object)
    self.email
  end


  validates :name, presence: true

  has_many :listings, dependent: :destroy
  
  has_one_attached :avatar

  def mailboxer_email(object)
    #return the model's email here
    :email
  end

end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
    def devise_error_messages!
      return '' if resource.errors.empty?
  
      messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
      sentence = I18n.t('errors.messages.not_saved', count: resource.errors.count, resource: resource.class.model_name.human.downcase)
  
      html = <<-HTML
      <div class="alert alert-danger alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <h4>#{sentence}</h4>
        #{messages}
      </div>
      HTML
  
      html.html_safe
    end
  end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/helpers/mailbox_helper.rb
module MailboxHelper
    def unread_messages_count
      # how to get the number of unread messages for the current user
      # using mailboxer
      # mailbox.inbox(:unread => true).count(:id, :distinct => true)
      mailbox.inbox(:unread => true).count(:id)

    end
  end

app/helpers/media_helper.rb
module MediaHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
  def recipients_options(chosen_recipient = nil)
    s = ''
    User.all.each do |user|
      s << "<option value='#{user.id}' data-img-src='#{gravatar_image_url(user.email, size: 50)}' #{'selected' if user == chosen_recipient}>#{user.name}</option>"
    end
    s.html_safe
  end

end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/_footer.html.erb
    <p>Copyright 2020</p>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg ">
      <div class="container">
  <a class="navbar-brand" href="/">ZineBloom</a>
  <button class="navbar-toggler custom-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item"><%= link_to "About", pages_about_path, class:"nav-link" %></li>
      <li class="nav-item"><%= link_to "Contact", pages_contact_path, class:"nav-link"  %></li>      
    </ul>
    <ul class="nav navbar-nav navbar-right">

      <% if cart_has_items %>
      <li class="nav-item ">
        <%= link_to cart_path(@cart), class:"nav-link btn btn-warning text-white" do%>
          <span class="icon is-small">
            <i class="fa fa-shopping-cart"></i>
          </span>
          <span class="">Cart <span class="">(<%= cart_count_over_one %>)</span>
          </span>
        <% end %>
      <% end%>
      </li>

      <% if user_signed_in? %>
        <%# dropdown menu %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= image_tag user_avatar(current_user, 20), class:"rounded-circle"%> <%= current_user.name %></a> 
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Manage Listings", seller_path, class:"dropdown-item" %>
            <%= link_to "Inbox (#{unread_messages_count})", mailbox_inbox_path, class:"dropdown-item" %>
            <%= link_to "Edit Profile", edit_user_registration_path, class:"dropdown-item" %>

            <div class="dropdown-divider"></div>
            <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class:"dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li><%= link_to "Sign Up", new_user_registration_path, class:"nav-link" %></li>
        <li><%= link_to "Sign In", new_user_session_path, class:"nav-link" %></li>
      <% end %>
    </ul>
  </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ZineBloom</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%# <script src="https://js.stripe.com/v3/"></script> %>
    <%= stylesheet_link_tag "//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" %>
    </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |name, msg| %>
      <br>
          <% if msg.is_a?(String) %>
            <div class="alert alert-<%= name.to_s == "notice" ? "success" : "danger" %> alert-dismissable">
              <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
              <%= content_tag :div, msg, :id => "flash_#{name}" %>
            </div>
          <% end %>
        <% end %>
      <br>
      <%= yield %>
      
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>